### ISSUE TITLE
Expunge your personal data from the repository

### ISSUE THREAD

**Issue by dixonary** [kevlened/remarkable-node#1]
Hey,

The token included in the file `test/index.js` includes your full name, personal email address and image. The token is base64-encoded and running it through a decoder reveals this information in plain text.

**Comment by kevlened** [comment]
Wow. I’m surprised I left those jwts in there. My full name and email are available elsewhere (I consider mine to be public info), but I’ll remove the tokens anyway. Fortunately, they’re expired. Thanks for the heads up.
